Ways to create numpy array

In [2]:
import numpy as np

In [2]:
# creating NUMPY array using list

np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

In [3]:
# creating numpy array using tuple 
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

Upcasting in NUMPY
- Upcasting in numpy refers automatic convrsion of data types when performing operations involving arrays of diffrent types, so that no data lost and the result has a compatible type that can hold all input values.

  - converting int to float is UPcasting - so no data loss  - if we have some float value present in the array
  - Converting float to int is DOwncasting

Two Dimensional numpy array


In [3]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# creating 2D array with ndmin
np.array([1,2,3,4], ndmin=2)   # the list should be minimum 2 dimension if not it will automatically convert 



array([[1, 2, 3, 4]])

In [ ]:
np.array([[[2,3,42,4]]], ndmin=3)    # minimum 3D array 

array([[[ 2,  3, 42,  4]]])

In [ ]:
np.array([2,3,4],dytype=complex)   # will convert in to complex real + imaginary


Data consisting more then one data type

In [ ]:
x=np.array([(1,2),(3,4.2)], dtype=[('a','i4'),('b',np.float32)])   # containing int and float both data type column name a and b 1,3 is int and 2,4.2 is float
x

array([(1, 2. ), (3, 4.2)], dtype=[('a', '<i4'), ('b', '<f4')])

In [9]:
x['a']

array([1, 3], dtype=int32)

In [10]:
x['b']

array([2. , 4.2], dtype=float32)

np.asarray - it only creates arrau when there is not array and ther is anything new 

In [11]:
a=[1,2]
np.asarray(a)

array([1, 2])

In [12]:
a=np.array([1,2])

In [13]:
a

array([1, 2])

In [ ]:
# checking is both the array are pointing the same memory address

np.asarray(a) is a 

True

In [ ]:
np.array(a) is a   # np.array creates a duplicate arrray is not any changes 

False

If data type is set , array is copied only if does not match 

In [18]:
a=np.array([1,2],dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [ ]:
np.asarray(a,dtype=np.float64) is a  # data dype changes that is whay it will create new array

False

 Creating an array x, with a refenrece Y and a copy z
 

In [21]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [23]:
y=x   # making refrence of x array 
y

array([1, 2, 3])

In [25]:
z=np.copy(x)   # creaing copy array of x
z

array([1, 2, 3])

In [ ]:
# lets mpdify some elements and see the change

x[0]=10
x  # will print the modified array

array([10,  2,  3])

In [28]:
y         # this will also print the modified array1


array([10,  2,  3])

In [ ]:
z            # this will print the old arry because it wonmt create new one

array([1, 2, 3])