In [ ]:
! pip install numpy 

Importing numpy 

In [2]:
import numpy as np 

In [2]:
np.__version__

'1.24.2'

Creating nD array

In [ ]:
# array1=np.array([1,2,3,4,5,5])
# array1   


array([1, 2, 3, 4, 5, 5])

In [ ]:
# type(array1)  # get the type of nd array

numpy.ndarray

In [ ]:
# help(np.array)   # to get help about the ibuild function and all will give suggestion

In [ ]:
# # to get the length we can use these in the array1


# array1.shape  # wil print the shape
# array1.size   # will peint the same 
# len(array1)   # this is alwo the same

6

CREATING 2D ARRAY


In [13]:
arrar2d=[[1,2,3],[4,5,6]]
arrar2d


[[1, 2, 3], [4, 5, 6]]

In [ ]:
# creatin 2d array using variables

# l1=[1,2,3,4]
# l2=[5,6,7,7]
# l3=[7,8,9,0]

# # this will print like 2d array 
# array3=np.array([[l1],[l2],[l3]])   # Rank 3
# print(array3)



[[[1 2 3 4]]

 [[5 6 7 7]]

 [[7 8 9 0]]]


In [ ]:
# Rank - Number of direction(axes) it has
# 1D array has rank 1
# 2D array has rank 2
# 3D array has rank 3

# np.array([1, 2, 3])      # Rank 1
# np.array([[1, 2], [3, 4]])  # Rank 2

In [ ]:
# diffrent ways to creating numpy array
 
# 1. np.array() - Create numpy arrau from python sequence as list or tuple

#arr=np.array([1,2,300]) 

# 2. np.fromitter() - creates one dimentional array from a iterable object

# text="hritik"
# arrayText=np.fromiter(text, dtype="U2")

# print(arrayText)

# # 3. numpy.arrange() return evenly spaced value withing a specific range 

# arr=np.arange(1,120,2, dtype=np.float32)

# # 4. numpy.linespace() return evenly spaced values between two limits 

# arrr=np.linspace(3,10,3,dtype=np.int32)

# # 5. numpy.empty() creates array  of given shape without initializing its values

# array=np.empty((2,3), dtype=np.int32)

# # 6. numpy.ones() create an array which filled with 1's 

# arrar=np.ones((3,4), dtype=np.int32)

# # 7. numpy.zeros() create an array filled with 0's

# arr=np.zeros((2,3), dtype=np.int32)


# int32 means 4 byte 


['h' 'r' 'i' 't' 'i' 'k']


CRETING 3D ARRAY

In [ ]:

# array3d=[[[1,2],[3,4]],[[4,5],[2,3]]]
# arra=np.array(array3d)

# arra.shape    # the shaoe is 2,2,2 whihc is shown because bracket containing 2 list and the list containing 2 elements
# print(arra[0,0,2])


(4, 1, 1)

- supoorted data types in numpy

NUMPY arrays nd array are homogeneous, meaning all elements must be of the same data type 


In [4]:
arr1111 = np.array([1, 2, 3], dtype=np.int32)
print(arr1111)

[1 2 3]


In [ ]:
arr2=np.array([1.2,3.4,1.4], dtype=np.float32)
arr2

# we can convert this to int means python can automatic detect a the the stores element is int or float 

arr3=np.array([1.2,3.3,8.9], dtype=np.int32)
print(arr3)   # we might lost some data but still converted into int

arr4=np.array([1,"2","3",4], dtype=np.int32)   # here the string element will be converted into int 
print(arr4) 




[1 3 8]
[1 2 3 4]


Record arrray or structured array
1. Structured array in numpy are homogeneous at the array level (each element has the same layout)
2. we want to specify a type and, optionally, a name on a paper per column basis, This make sorting and filtering even more powerful, and it can feel similar to working with data in Excel and CSVs or relationsal databses  

In [5]:
records=[("hritik",12,34),
         ("tanmay",34,23),
         ("abhi",24,122)]
print(records)

[('hritik', 12, 34), ('tanmay', 34, 23), ('abhi', 24, 122)]


Converting the string elements in the list as int and keeping string element as string usign some methods


In [6]:
array_records=np.array(records,dtype=[("name","U15"),("age",np.int32),("marks",np.int32)])
array_records

array([('hritik', 12,  34), ('tanmay', 34,  23), ('abhi', 24, 122)],
      dtype=[('name', '<U15'), ('age', '<i4'), ('marks', '<i4')])

We can specify the data type in sevral equivalent ways.
1. Using NUMPY type string ( compact )- [("name","U15"), ("age",np.int32),("marks",np.int32)]
2. Using NUMPY type object (recommended)- [("name",np.unicode_),("age",np.int32),("marks",np.int32)]
3. Mixing python build in types and numpy types - [("name",str),("age",int),("marks",np.int32)]




In [ ]:
print(array_records[0])   # print the first record of the dataset

('hritik', 12, 34)


In [ ]:
print(array_records["name"])          # will print the names of the records in the array 

['hritik' 'tanmay' 'abhi']


Homogeneous array allow:
1. Vecotrized Operations
2. Effictient memeory layout (continuous block)
3. Fast computation using C under the hood 

- NumPy is designes for array of fixed size elements - typically numerical data types (interger, floats  but also supports, booleans, dates and custom structured types)

- All elements in numpy array share the same data type (dtype)
- The data is stored in a contigeous block of memory for efficiency 

It cansupport hetrogeneous type using object or structured  dtype, but these lose most perormance benifits.

In [10]:
het=np.array([5,4.5,'True','c'], dtype=object)   
het         # convert all elements into objcets 

array([5, 4.5, 'True', 'c'], dtype=object)

In [ ]:
het.dtype   # this shows object data type

dtype('O')

In [14]:
het[0]

5

In [ ]:
print(type(het[0]))     # this will show int type because of first element 

<class 'int'>
