## creating numpy array using buildin function


# arrange and linespace

In [2]:
import numpy as np

In [ ]:
# range (start,stop,step)
# np.arrange(start,stop,step,dtype)

list(range(1,10,2)) # using range only 

[1, 3, 5, 7, 9]

In [ ]:
# np.arrange

np.arange(1,50,5,dtype=np.float128)

# 1 byte = 8 bit
# f is short form of np.float32 = 4 bytes
# float is used in python  usually 64 bit 
# float64 means 8 bytes

linespace


In [3]:
# np.linespace(start, stop, num=50, endpoint=True, retsteps=False, dtype=None, axis=0)

# 21 linearly spaced numbers bwtween 1 to 5 
np.linspace(1,5,21)  # by default it is float 

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

In [ ]:
# here we have typecasted the values to int so values will be lost 


np.linspace(1,5,21,dtype=np.int32)   

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5],
      dtype=int32)

# logspace
- np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=none)
    - start → Starting exponent
    - stop → Ending exponent
    - num → Number of values to generate
    - base → Base of the logarithm (default is 10)

In [14]:
# np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=none)
arr=np.logspace(1,3,3)
print(arr)

[  10.  100. 1000.]


In [15]:
arr=np.logspace(0,4,5)
print(arr)

# output means
1
10
100
1000
10000

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


10000

In [16]:
np.logspace(1,5,5,base=2)   


# Output:

# [ 2.  4.  8. 16. 32.]

# Because it calculates:

# 2¹ = 2
# 2² = 4
# 2³ = 8
# 2⁴ = 16
# 2⁵ = 32

array([ 2.,  4.,  8., 16., 32.])

In [17]:
# it is useful when your data spans many orders of magnitude, such as 
# - signal processing 
# - physics
# - Machine learning 
# - sciencetifuc computation
# - Frequency analysis 

# for example when testing learning rates in machine learning 
arr=np.logspace(-4,0,5)
print(arr)

# Output:

# [0.0001 0.001 0.01 0.1 1. ]

# Instead of checking every value between 0.0001 and 1, you test values that increase by powers of 10, which is much more practical.


[1.e-04 1.e-03 1.e-02 1.e-01 1.e+00]


In [18]:
np.linspace(1,1024,num=5,dtype=np.int32)



array([   1,  256,  512,  768, 1024], dtype=int32)

In [19]:
np.logspace(0,10,num=5, base=2,dtype=np.int32)


array([   1,    5,   32,  181, 1024], dtype=int32)

In [20]:
# creating np array from a list or tuple
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)



[1 2 3 4 5]


In [21]:
# Creating array filled with zeros

arr=np.zeros((2,3))  # 2- rows and 3 columns
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
# Creating an array filled with ones.

arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
# creating an array with uninitialized values 
arr1=np.empty((2,3))
print(arr1)

# values are unpredictable because numpy dont initialize them 

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# np.full - crating a array filled with a specific value 
arr=np.full((2,4),5)   # filled with 5
print(arr)

[[5 5 5 5]
 [5 5 5 5]]


In [25]:
# np.arange 
arr=np.arange(1,11) # prints value in a range 
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


-- Identity matrix


In [ ]:
#  creating an identity matrix  
# 1 in diagonal

diagonalArray=np.eye(3)    # will create a 3 x 3 matrix
print(diagonalArray)


# Another way to create  an IDENTITY matrix 

arr=np.identity(5)  # using identity()
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
# create a diagonal matirx

arr=np.diag([1,2,3])   # diagonal matrix with diffrent numbers 
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
# to print the random numbers etween 0 and 1


arr=np.random.rand(3,2) 
print(arr)

[[0.98560929 0.52129894]
 [0.60447412 0.37223646]
 [0.82209637 0.16157094]]


In [40]:
# no.random.randint()

arr=np.random.randint(1,100 , (2,3))  # print random values bw 1- 100

print(arr)


[[23 19 49]
 [14 65 81]]


In [ ]:
# np.random.randn() 
# random number form a random distribution

arr=np.random.randn(3,4)
print(arr)

[[-0.25122228  0.80197864 -0.31382218 -0.19678355]
 [ 0.46504713 -0.43379564  0.60673446  0.69591387]
 [-0.14463962  0.82279972 -1.39569761  0.46354031]]


In [ ]:
# np.random.choice() 
# randomly selects value 
arr=np.random.choice([10,20,30],size=5)   # can select random values 5 times from the input or defined list 
print(arr)

[30 30 10 20 30]


In [44]:
# np.copy()
# creates a copy of the array

a=np.array([1,2,3,4])
arr=np.copy(a)
print(arr)

[1 2 3 4]


In [ ]:
# np.shape() to give a shape of an array
arr=np.arange(12).reshape(4,3) # here rearanging the value form 1D to 2D rashaping into matrix
 
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# np.flatten()
# converts a multidimentional array into 1D array 

arr=np.array([[1,2,3],[4,5,6]])
print(arr.flatten())    # this is how we use the function


[1 2 3 4 5 6]


In [53]:
# np.ravel()

# returns a flatend view of the array

arr=np.array([[1,2,3],[4,5,6]])
print(arr.ravel())

[1 2 3 4 5 6]


In [55]:
# np.concatenate()

# Joins arraya

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[5,6,7]])

print(np.concatenate((a,b)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [5 6 7]]


In [56]:
# np.stack()

# stacks array along a new axis

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[5,6,7]])

print(np.stack((a,b)))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [5 6 7]]]


# Diagonal . Triangular , Lower Triangular , and Upper Triangular Matrix

In [ ]:
# to extract diagonal elements 
# Diagonal - Meanig where i = j 
arr=np.array([[1,2,3],[5,6,7],[8,9,10]])

print("Diagonal Elements are",np.diag(arr))


Diagonal Elements are [ 1  6 10]


In [ ]:
# To create a diagonal matrix using diagonal elements for this arrau
np.diag(np.diag(arr))   # using np.diag 2 times one for extracting the diagonal elements another one is for trnasforming 

array([[ 1,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 10]])

In [ ]:
# Lower Triangular matrix

np.tril(arr)  # tri = Triangular , l = lower

array([[ 1,  0,  0],
       [ 5,  6,  0],
       [ 8,  9, 10]])

In [64]:
# Upper Triangular matrix

np.triu(arr)   # tri= Triangular , u = upper

array([[ 1,  2,  3],
       [ 0,  6,  7],
       [ 0,  0, 10]])

In [2]:
# For a non square matrix 
import numpy as np
a=np.array([[1,2,4,5],[2,4,5,7],[6,7,8,9]])
print(a)

[[1 2 4 5]
 [2 4 5 7]
 [6 7 8 9]]


In [ ]:
# to print diagonal for non square matrix
np.diag(a) # print diagonal element where i = j because it is 

array([1, 4, 8])