Read and Write a data from a file   
txt files and csv files

In [1]:
import numpy as np

In [ ]:
data=np.loadtxt("data.txt",delimiter=',')   # loading data.txt using numpy
data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [3]:
data=data**2       # makeing square of all data in the txt file
data

array([[  1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.],
       [ 81., 100., 121., 144.]])

In [ ]:
np.savetxt("output_data.txt",data,fmt="%i")   # saving output file as output data in integer format 

Binary files (.npy, .npz)

In [6]:
arr=np.array([1,2,3,4])
np.save("binary_array.npy",arr)


In [7]:
arr=np.load("binary_array.npy")
print(arr)

[1 2 3 4]


In [10]:
# if we have two array and we want to save thin into binary file 
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
np.savez("TwoArrinBinary.npz",arr1=a,arr2=b)   # notice we have used savez to save more then one array here and arr1 and arr2 for refrence

In [ ]:
# reading the file wiht multiple array
data=np.load("TwoArrinBinary.npz")
print(data["arr1"])  # we can also read the arrays individually or full as per our requirment
# print(data["arr2"])  

[1 2 3 4]


| File Format | Read Function | Write Function | Notes |
|-------------|---------------|----------------|-------|
| `.txt` / `.csv` | `loadtxt()` / `genfromtxt()` | `savetxt()` | Use delimiter for custom separators |
| `.npy` | `load()` | `save()` | For single array (binary) |
| `.npz` | `load()` | `savez()` / `savez_compressed()` | For multiple arrays |

---

# Advantages of `.npy` and `.npz` over Text Files

| Feature | `.npy` / `.npz` (Binary) | `.txt` / `.csv` (Text) |
|---------|---------------------------|-------------------------|
| **Efficiency** | Much faster to read/write | Slower I/O |
| **Storage Size** | More compact | Larger file size |
| **Multiple Arrays** | `.npz` can store many arrays in one file | Not supported; need multiple files |
| **No Parsing Needed** | Directly loads as NumPy array | Needs delimiter, dtype parsing |
| **More Reliable** | No risk of formatting issues | Sensitive to extra spaces, missing values, etc. |

# - numpy.fromfunction

In [ ]:
np.fromfunction(lambda i, j:i==j,(3,3),dtype=int)   # where i==j it is printing true else printing false

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

- A new 1-D array initialized from text data in a stirng 


In [ ]:
np.fromstring('1 2',dtype=int, sep=' ') # sep - seprator means seprates the values 

array([1, 2])

# create a record array from a (flat) list of arrays

In [19]:
x1=[1,2,3]
x2=[4,0,5.0,6.0]
x3=['a','b','c']



In [ ]:
# list of tuple

list(zip(x1,x2,x3))  # zip will make a tuple with every element from the list start from first whihc we can convert into numpy array

[(1, 4, 'a'), (2, 0, 'b'), (3, 5.0, 'c')]

In [ ]:
# lets create the same using numpy

r=np.array(list(zip(x1,x2,x3)), dtype=[('a','i4'),('b','f4'),('c','U1')])   # have given the column ref and dtype here 

In [22]:
r

array([(1, 4., 'a'), (2, 0., 'b'), (3, 5., 'c')],
      dtype=[('a', '<i4'), ('b', '<f4'), ('c', '<U1')])

In [ ]:
r['a']  # to access first column 

# Although nupy store homogeneous data we can store hetrogeneous data using record array  explained in the prev code

array([1, 2, 3], dtype=int32)

# creating a 2d array and working on some functions 

In [ ]:
myMat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(myMat)

print("type of the matrix is",type(mat))    # every array in the numpy type will be nd array 

 # ndim is use to get the dimension of the matrix 2 for matrix 1 for vector 
print("Dimension of the matrix is ",mat.ndim,sep=' ')  

type of the matrix is <class 'numpy.ndarray'>
Dimension of the matrix is  2


In [29]:
# size gives the total no of elements 
print("size of the matrix",mat.size,sep=' ')


# shape givea the number of element along each axes (dimension)
print("shape of the matrix is",mat.shape,sep=' ')

# dtype gives the datatype contained in the array 
print("data type in the mtrox is ", mat.dtype,sep=' ')


size of the matrix 9
shape of the matrix is (3, 3)
data type in the mtrox is  int64
