## 1 . Linear Space:
  - Values evenly seprated in linear space 
  - Regular interval
  - The diffrence between consecutive number is constant
  _Example:-
        - Number of clusters in K- means clustring

          k=[1,2,3,4,5,6,7,8,9,10]  # values are spearated evenly/constantly 

        - Use avove k value to evaluate clustring performance 

                            K
                            |
        <---|---|---|---|---|---|---|---|---|---|--->
        0   1   2   3   4   5   6   7   8   9   10

        - look for optimal k using matrices ( within cluster sum of squares )

## 2. Logarithmic Space

- Generates numbers that are evenly spaced on a logarithmic space.
- The ratio between consecutive numbers is constant.
- **Example:** Finding optimal learning rate (α)

```python
α = [0.00001, 0.0001, 0.001, 0.01, 0.1]
```

- Use the above α values to evaluate the best learning rate.

```text
0.00001 ───► 0.0001 ───► 0.001 ───► 0.01 ───────────────────► 0.1
```

# can see the diffrence is same which is evenly seprated 

# Logarithmic Space (`np.logspace()`)

## Definition

`np.logspace()` is a NumPy function that generates numbers that are **evenly spaced on a logarithmic scale**.

Unlike `np.linspace()`, where the **difference** between consecutive values is constant, in `np.logspace()` the **ratio** between consecutive values is constant.

---

## Key Points

- Generates numbers on a **logarithmic scale**.
- The **ratio** between consecutive numbers remains constant.
- Useful when values span **multiple orders of magnitude**.
- Commonly used in **Machine Learning**, **Deep Learning**, **Signal Processing**, and **Scientific Computing**.

---

## Difference Between `linspace()` and `logspace()`

| `np.linspace()` | `np.logspace()` |
|-----------------|-----------------|
| Equal difference between values | Equal ratio between values |
| Linear scale | Logarithmic scale |
| Used for normal intervals | Used for exponential intervals |

### Example

**Linear Space**

```python
import numpy as np

np.linspace(1, 10, 5)
```

**Output**

```python
array([ 1.  , 3.25, 5.5 , 7.75, 10. ])
```

Difference:

```text
+2.25  +2.25  +2.25  +2.25
```

---

**Logarithmic Space**

```python
import numpy as np

np.logspace(0, 4, 5)
```

**Output**

```python
array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04])
```

Ratio:

```text
×10  ×10  ×10  ×10
```

---

## Syntax

```python
np.logspace(start, stop, num=50, base=10)
```

### Parameters

| Parameter | Description |
|-----------|-------------|
| `start` | Starting exponent |
| `stop` | Ending exponent |
| `num` | Number of samples |
| `base` | Base of logarithm (default = 10) |

---

## Example 1

```python
import numpy as np

arr = np.logspace(1, 3, 3)

print(arr)
```

**Output**

```python
[  10.  100. 1000.]
```

Explanation:

```text
10¹ = 10
10² = 100
10³ = 1000
```

---

## Example 2

```python
import numpy as np

arr = np.logspace(0, 5, 6)

print(arr)
```

**Output**

```python
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]
```

---

## Machine Learning Use Case

One of the most common uses of `np.logspace()` is to generate **learning rates** for hyperparameter tuning.

Example:

```python
import numpy as np

learning_rates = np.logspace(-5, -1, 5)

print(learning_rates)
```

**Output**

```python
[1.e-05 1.e-04 1.e-03 1.e-02 1.e-01]
```

Equivalent values:

```text
0.00001
0.0001
0.001
0.01
0.1
```

These values are commonly tested to find the **optimal learning rate (α)** for training machine learning and deep learning models.

---

## Why Not Use `linspace()` for Learning Rates?

Suppose you use:

```python
np.linspace(0.00001, 0.1, 5)
```

Output:

```text
0.00001
0.0250075
0.050005
0.0750025
0.1
```

Notice that important values like

- 0.0001
- 0.001
- 0.01

are missing.

Using `logspace()` gives exponentially spaced values, which are much more useful for hyperparameter tuning.

---

## Real-World Applications

- Hyperparameter tuning
- Learning rate selection
- Regularization parameter (`C`)
- Gamma values in Support Vector Machines (SVM)
- Scientific simulations
- Signal processing
- Frequency analysis

---

## Visual Representation

```text
Linear Space

1 ----- 3 ----- 5 ----- 7 ----- 9
(Equal Difference)


Logarithmic Space

1 ---- 10 ---- 100 ---- 1000 ---- 10000
(Equal Ratio)
```

---

# Interview Questions

### 1. What is `np.logspace()`?

**Answer:**

`np.logspace()` generates numbers that are evenly spaced on a logarithmic scale. The ratio between consecutive numbers is constant.

---

### 2. What is the difference between `np.linspace()` and `np.logspace()`?

| `linspace()` | `logspace()` |
|--------------|--------------|
| Constant difference | Constant ratio |
| Linear scale | Logarithmic scale |

---

### 3. Why is `np.logspace()` used for learning rates?

**Answer:**

Learning rates usually vary over several orders of magnitude (e.g., `10⁻⁵` to `10⁻¹`). `np.logspace()` generates values that efficiently cover this wide range, making it easier to find the optimal learning rate.

---

### 4. What is the default base in `np.logspace()`?

**Answer:**

The default base is **10**.

---

### 5. What does this code output?

```python
import numpy as np

np.logspace(1, 3, 3)
```

**Answer**

```python
array([10., 100., 1000.])
```

---

## Summary

- `np.logspace()` creates numbers on a logarithmic scale.
- The ratio between consecutive values is constant.
- It is widely used for hyperparameter tuning in machine learning.
- Default logarithm base is **10**.
- Best suited when values span several orders of magnitude.

# 3. Matrix

- In **mathematics**, a **matrix is always 2-dimensional** (rows × columns).
- In **NumPy**, arrays are classified based on their dimensions:

| Array | Representation | Shape |
|-------|----------------|-------|
| **1D Array** | Vector | `(n,)` |
| **2D Array** | Matrix | `(m × n)` |
| **3D Array or Higher** | Tensor | `(d × m × n)` or higher |

> **Note:** A matrix is simply a collection of elements arranged in **rows and columns**.

---

## 2D Array (Matrix)

### NumPy Style

```python
[
    [5, 10, 15],
    [2,  4,  6],
    [5,  7,  2]
]
```

### Mathematical Representation

```text
[ 5  10 15 ]
[ 2   4  6 ]
[ 5   7  2 ]
```

- **Dimension:** 2
- **Shape:** `(3 × 3)`
- **Rows = 3**
- **Columns = 3**
- Since **m = n**, it is a **Square Matrix**.

---

## Types of Matrix Based on Shape

Generally, matrices are classified based on their **shape (rows × columns)**.

### 1. Square Matrix

- Number of rows = Number of columns.
- Condition:

```text
m = n
```

Examples:

```text
2 × 2
3 × 3
4 × 4
5 × 5
```

---

### 2. Rectangular Matrix

- Number of rows ≠ Number of columns.
- Condition:

```text
m ≠ n
```

Examples:

```text
2 × 3
3 × 5
4 × 2
```

---

# Diagonal of a Matrix

## Main Diagonal

The **main diagonal** consists of elements where:

```text
i = j
```

That means the **row index** and **column index** are the same.

Example:

```text
[ 5  10 15 ]
[ 2   4  6 ]
[ 5   7  2 ]
```

Main diagonal elements:

```text
5 → 4 → 2
```

---

## Diagonals Parallel to the Main Diagonal

Diagonals parallel to the main diagonal are identified using the **offset (`k`)**.

```text
k = 0   → Main diagonal

k = 1   → One diagonal above the main diagonal
k = 2   → Two diagonals above the main diagonal

k = -1  → One diagonal below the main diagonal
k = -2  → Two diagonals below the main diagonal
```

**Example**

```text
[ 5 10 15 ]
[ 2  4  6 ]
[ 5  7  2 ]

Main diagonal (k=0):    5, 4, 2
Above diagonal (k=1):   10, 6
Below diagonal (k=-1):  2, 7
```

---

# Special Types of Square Matrices

> These matrices are **defined only for square matrices (m = n).**

---

## 1. Diagonal Matrix

A matrix in which **all non-diagonal elements are zero**.

Example:

```text
[ 5 0 0 ]
[ 0 4 0 ]
[ 0 0 2 ]
```

**Condition**

- Main diagonal can contain **any value**.
- Every other element must be **0**.

---

## 2. Identity Matrix

A special type of diagonal matrix whose **main diagonal elements are all 1**.

Example:

```text
[ 1 0 0 ]
[ 0 1 0 ]
[ 0 0 1 ]
```

**Condition**

- Main diagonal = **1**
- Remaining elements = **0**

> Every Identity Matrix is a Diagonal Matrix, but every Diagonal Matrix is **not** an Identity Matrix.

---

## 3. Upper Triangular Matrix

A matrix in which **all elements below the main diagonal are zero**.

Example:

```text
[ 5 10 15 ]
[ 0  4  6 ]
[ 0  0  2 ]
```

**Condition**

- Zero **below** the main diagonal.
- Elements on and above the main diagonal can be any value.

---

## 4. Lower Triangular Matrix

A matrix in which **all elements above the main diagonal are zero**.

Example:

```text
[ 5  0  0 ]
[ 2  4  0 ]
[ 5  7  2 ]
```

**Condition**

- Zero **above** the main diagonal.
- Elements on and below the main diagonal can be any value.

---

## Summary

| Matrix Type | Condition |
|-------------|-----------|
| **Square Matrix** | Rows = Columns |
| **Rectangular Matrix** | Rows ≠ Columns |
| **Diagonal Matrix** | All non-diagonal elements are 0 |
| **Identity Matrix** | Diagonal elements are 1, others are 0 |
| **Upper Triangular Matrix** | All elements below the main diagonal are 0 |
| **Lower Triangular Matrix** | All elements above the main diagonal are 0 |



# Random Number Generation in NumPy

Random number generation is the process of generating numbers randomly from a specific set of values based on a **probability distribution**.

In NumPy, random numbers are primarily generated using two major types of distributions:

1. **Uniform Distribution (`np.random.rand()`)**
2. **Normal (Gaussian) Distribution (`np.random.randn()`)**

---

# 1. Uniform Distribution (`np.random.rand()`)

In a **Uniform Distribution**, every number within a given range has an **equal probability** of being selected.

> **Key Point:** Every possible value is equally likely to occur.

---

## Examples

### Example 1

Pick a random integer from **[1, 10]**.

Each number has an equal probability of being selected.

```text
Probability = 1/10
```

---

### Example 2

Roll a fair dice one time.

Possible outcomes:

```text
1   2   3   4   5   6
```

Each outcome has an equal probability.

```text
Probability = 1/6
```

---

## Frequency Plot (10,000 Dice Rolls)

If you roll a fair dice **10,000 times**, each face appears approximately the same number of times.

```text
Frequency
^
|  +---+---+---+---+---+---+
|  |   |   |   |   |   |   |
|  |   |   |   |   |   |   |  ← Equal Probability
|  |   |   |   |   |   |   |
+--+---+---+---+---+---+---+---->
   1   2   3   4   5   6
         Dice Outcomes
```

Since every outcome is equally likely, the graph forms a **flat (uniform)** distribution.

---

# 2. Normal (Gaussian) Distribution (`np.random.randn()`)

In a **Normal Distribution**, values near the **mean (average)** have a much higher probability of occurring than values far from the mean.

This distribution is commonly known as the **Bell Curve**.

> **Key Point:** Most values are concentrated around the center (mean).

---

## Real-World Example: Human Height

Suppose you measure the height of **100,000 adults**.

- Extremely short heights (e.g., **2 ft**) occur very rarely.
- Extremely tall heights (e.g., **7–8 ft**) also occur very rarely.
- Most people have heights around the **average (e.g., 5.4 ft)**.

Therefore, the graph forms a **bell-shaped curve**.

---

## Frequency Plot (Bell Curve)

```text
Frequency
^
|
|             * *
|           *     *
|         *         *
|       *             *
|     *                 *
|   *                     *     ← Bell-shaped Curve
+-------------------------------------------->
Extreme            Mean              Extreme
 Low              (Peak)               High
```

Most values lie near the **mean**, while very small and very large values occur less frequently.

---

## Summary

| Uniform Distribution | Normal Distribution |
|----------------------|---------------------|
| Equal probability for every value | Higher probability near the mean |
| Flat distribution | Bell-shaped distribution |
| `np.random.rand()` | `np.random.randn()` |
| Example: Rolling a fair dice | Example: Human height |